# Generated by Django 2.0 on 2019-10-01 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, upload_to='media')),
                ('nome_arquivo', models.CharField(max_length=100, verbose_name='Nome do Arquivo')),
                ('descricao', models.TextField(verbose_name='Descrição do Arquivo')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoExtensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('resumo_curso', models.TextField(verbose_name='Resumo do Curso')),
                ('area_tematica', models.CharField(max_length=100, verbose_name='Área Temática')),
                ('data_inicio', models.DateField(verbose_name='Período de Execução Inicial')),
                ('data_final', models.DateField(verbose_name='Período de Execução Final')),
                ('data_inscricoes_inicial', models.DateField(verbose_name='Período Inicial das Inscrições')),
                ('data_inscricoes_final', models.DateField(verbose_name='Período Final das Inscrições')),
                ('area_conhecimento', models.CharField(max_length=100, verbose_name='Área de Conhecimento')),
                ('tema', models.CharField(max_length=100, verbose_name='Tema')),
                ('possui_cunho_social', models.CharField(max_length=100, verbose_name='Possui Cunho Social')),
                ('vagas_participantes', models.CharField(max_length=5, verbose_name='Vagas Participantes')),
                ('publico_alvo', models.CharField(max_length=100, verbose_name='Público Alvo')),
                ('carga_horaria', models.CharField(max_length=10, verbose_name='Carga Horária')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno')),
                ('periodo_letivo', models.CharField(max_length=100, verbose_name='Ano Letivo')),
                ('foto_curso', models.ImageField(blank=True, default='default.png', upload_to='media')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='EquipeParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('bolsista', models.CharField(max_length=200, verbose_name='Bolsista')),
                ('titulacao', models.CharField(max_length=200, verbose_name='Titulação')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipe',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('curso_extensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensao.CursoExtensao')),
            ],
            options={
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outros', 'Outros')], max_length=9, verbose_name='Sexo')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Filiação - Nome da Mãe')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Filiação - Outro Responsável')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('estado_nascimento', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Cantaria'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='Estado Nascimento')),
                ('municipio_nascimento', models.CharField(max_length=100, verbose_name='Minicípio de Nascimento')),
                ('identidade_candidato', models.CharField(max_length=100, verbose_name='Identidade do candidato')),
                ('titulo', models.CharField(max_length=12, verbose_name='Título de Eleitor')),
                ('reservista', models.CharField(max_length=12, verbose_name='Carteira de Reservista')),
                ('data_identidade', models.DateField(verbose_name='Data de Emissão Identidade')),
                ('orgao_emissor', models.CharField(choices=[('SSP', ' Secretaria de Segurança Pública'), ('Cartório Civil', 'Cartório Civil '), ('Polícia Federal ', 'Polícia Federal '), ('Detran', 'Detran'), ('Outros', 'Outros')], max_length=100, verbose_name='Órgão Emissor')),
                ('uf_identidade', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Cantaria'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='UF da Identidade')),
                ('municipio_identidade', models.CharField(max_length=100, verbose_name='Município da Identidade')),
                ('pais_origem', models.CharField(blank=True, max_length=100, verbose_name='País de Origem')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade_endereco', models.CharField(max_length=100, verbose_name='Cidade deste endereço')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('telefone_residencial', models.CharField(blank=True, max_length=15, verbose_name='Telefone Residencial')),
                ('telefone_celular', models.CharField(max_length=15, verbose_name='Telefone Celular')),
                ('foto_perfil', models.ImageField(blank=True, upload_to='media')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situação',
            },
        ),
        migrations.CreateModel(
            name='SituacaoInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_inscricao', models.CharField(max_length=50, verbose_name='Situação da Inscrição')),
            ],
            options={
                'verbose_name': 'Situação da Inscrição',
                'verbose_name_plural': 'Situação da Inscrição',
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensao.Participante'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='situacao_inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensao.SituacaoInscricao'),
        ),
        migrations.AddField(
            model_name='cursoextensao',
            name='equipe_participante',
            field=models.ManyToManyField(to='extensao.EquipeParticipante'),
        ),
        migrations.AddField(
            model_name='cursoextensao',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensao.Situacao'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivo', to='extensao.CursoExtensao'),
        ),
    ]
