# Generated by Django 2.0 on 2019-05-20 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoExtensao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100, verbose_name='Nome do curso')),
                ('grade_area_conhecimento', models.CharField(max_length=100, verbose_name='Grade Área de Conhecimento')),
                ('area_tematica', models.CharField(max_length=100, verbose_name='Área Temática')),
                ('data_inicio', models.DateField(verbose_name='Periodo de execução inicial')),
                ('data_final', models.DateField(verbose_name='Periodo de execução final')),
                ('area_conhecimento', models.CharField(max_length=100, verbose_name='Área de Conhecimento')),
                ('tema', models.CharField(max_length=100, verbose_name='Tema')),
                ('possui_cunho_social', models.CharField(max_length=100, verbose_name='Possui Cunho Social')),
                ('vagas_participantes', models.CharField(max_length=5, verbose_name='Vagas Participantes')),
                ('publico_alvo', models.CharField(max_length=100, verbose_name='Público Alvo')),
                ('carga_horaria', models.CharField(max_length=10, verbose_name='Carga Horária')),
                ('foto_curso', models.ImageField(blank=True, default='default.png', upload_to='media')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projetos de Extensão',
                'verbose_name_plural': 'Projetos de Extensão',
            },
        ),
        migrations.CreateModel(
            name='EquipeParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('bolsista', models.CharField(max_length=200, verbose_name='Bolsista')),
                ('titulacao', models.CharField(max_length=200, verbose_name='Titulação')),
            ],
            options={
                'verbose_name': 'Equipe Participante',
                'verbose_name_plural': 'Equipe Participante',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('curso_extensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensao.CursoExtensao')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo*')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outros', 'Outros')], max_length=9, verbose_name='Sexo')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Filiação - Nome da Mãe*')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Filiação - Outro Responsável')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento*')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade*')),
                ('estado_nascimento', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Cantaria'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='Estado Nascimento')),
                ('municipio_nascimento', models.CharField(max_length=100, verbose_name='Minicípio de Nascimento')),
                ('identidade_candidato', models.CharField(max_length=100, verbose_name='Identidade do candidato*')),
                ('data_identidade', models.DateField(verbose_name='Data de Emissão Identidade*')),
                ('orgao_emissor', models.CharField(choices=[('SSP', ' Secretaria de Segurança Pública'), ('Cartório Civil', 'Cartório Civil '), ('Polícia Federal ', 'Polícia Federal '), ('Detran', 'Detran'), ('Outros', 'Outros')], max_length=100, verbose_name='Órgão Emissor*')),
                ('uf_identidade', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Cantaria'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='UF da Identidade*')),
                ('municipio_identidade', models.CharField(max_length=100, verbose_name='Município da Identidade*')),
                ('pais_origem', models.CharField(blank=True, max_length=100, verbose_name='País de Origem')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro*')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade_endereco', models.CharField(max_length=100, verbose_name='Cidade deste endereço*')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('zona', models.CharField(max_length=100, verbose_name='Zona')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail*')),
                ('telefone_residencial', models.CharField(max_length=15, verbose_name='Telefone Residencial')),
                ('telefone_celular', models.CharField(max_length=15, verbose_name='Telefone Celular')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situação',
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensao.Participante'),
        ),
        migrations.AddField(
            model_name='cursoextensao',
            name='equipe_participante',
            field=models.ManyToManyField(to='extensao.EquipeParticipante'),
        ),
        migrations.AddField(
            model_name='cursoextensao',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extensao.Situacao'),
        ),
    ]
