# Generated by Django 2.0 on 2019-10-01 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoextensao',
            name='situacao',
            field=models.ForeignKey(default='Novo', on_delete=django.db.models.deletion.PROTECT, to='extensao.Situacao'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='situacao_inscricao',
            field=models.ForeignKey(default='Em Análise', on_delete=django.db.models.deletion.PROTECT, to='extensao.SituacaoInscricao'),
        ),
    ]
