# Generated by Django 2.0 on 2019-10-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0002_auto_20191001_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='situacao_inscricao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='extensao.SituacaoInscricao'),
        ),
    ]
