# Generated by Django 2.0 on 2019-10-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0003_auto_20191001_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoextensao',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='extensao.Situacao'),
        ),
    ]
