# Generated by Django 2.0 on 2019-10-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensao', '0004_auto_20191001_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_oferta', models.CharField(max_length=100, verbose_name='Nome da Oferta')),
                ('resumo_oferta', models.TextField(verbose_name='Resumo da Oferta')),
                ('data_inicio', models.DateField(verbose_name='Período de Execução Inicial')),
                ('data_final', models.DateField(verbose_name='Período de Execução Final')),
                ('data_inscricoes_inicial', models.DateField(verbose_name='Período Inicial das Inscrições')),
                ('data_inscricoes_final', models.DateField(verbose_name='Período Final das Inscrições')),
                ('area_conhecimento', models.CharField(max_length=100, verbose_name='Área de Conhecimento')),
                ('vagas_participantes', models.CharField(max_length=5, verbose_name='Vagas Participantes')),
                ('publico_alvo', models.CharField(max_length=100, verbose_name='Público Alvo')),
                ('carga_horaria', models.CharField(max_length=10, verbose_name='Carga Horária')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno')),
                ('periodo_letivo', models.CharField(max_length=100, verbose_name='Ano Letivo')),
                ('foto_oferta', models.ImageField(blank=True, default='default.png', upload_to='media')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('equipe_participante', models.ManyToManyField(to='extensao.EquipeParticipante')),
                ('situacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='extensao.Situacao')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.RemoveField(
            model_name='cursoextensao',
            name='equipe_participante',
        ),
        migrations.RemoveField(
            model_name='cursoextensao',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='curso_extensao',
        ),
        migrations.DeleteModel(
            name='CursoExtensao',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='oferta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='arquivo', to='extensao.Oferta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='oferta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='extensao.Oferta'),
            preserve_default=False,
        ),
    ]
